import type { CSSProperties } from "react";
import Image from "next/image";

import { cn } from "../../lib/utils";

/**
 * The IAESTE LC Lleida mark.
 *
 * Every app used to reach for `<Image src="/logos/...">` with its own filename
 * and its own idea of which file was current, so the header, the footer and the
 * two registration screens drifted onto four different rasters of the same
 * logo. This is the one place that knows the filenames.
 *
 * The files it points at are generated by `assets/brand/generate-brand.mjs`
 * into `public/brand/` of every app, under identical names — that is what lets
 * a component in a shared package hardcode absolute paths and still resolve in
 * whichever app renders it.
 */

type LogoVariant = "icon" | "horizontal";
type LogoColour = "navy" | "white";

/**
 * `ratio` is height ÷ width of the shipped asset, so a caller only ever picks a
 * width and cannot letterbox the mark by mismatching the pair.
 *
 * `defaultWidth` is a rendered width, not the asset's own: it is what
 * `next/image` builds the srcset around, so leaving it near real usage is the
 * difference between serving a 200px logo and a 1600px one.
 */
const VARIANTS = {
  icon: {
    ratio: 1,
    defaultWidth: 64,
    navy: "/brand/icon-navy.png",
    white: "/brand/icon-white.png",
  },
  horizontal: {
    ratio: 478 / 1600,
    defaultWidth: 320,
    navy: "/brand/wordmark-horizontal-navy.png",
    white: "/brand/wordmark-horizontal-white.png",
  },
} as const satisfies Record<
  LogoVariant,
  { ratio: number; defaultWidth: number } & Record<LogoColour, string>
>;

export interface LogoProps {
  variant?: LogoVariant;
  /** `white` is the knockout, for navy grounds and photography. */
  color?: LogoColour;
  /** Rendered width in px. Height follows from the variant's aspect ratio. */
  width?: number;
  /**
   * Defaults to the committee's name. Pass `""` where the mark is decorative
   * because adjacent text already names it — the hero, where "iaeste lc lleida"
   * is set in live type around it.
   */
  alt?: string;
  className?: string;
  /** For a rendered width that animates, which Tailwind cannot express. */
  style?: CSSProperties;
  priority?: boolean;
  sizes?: string;
}

export function Logo({
  variant = "icon",
  color = "navy",
  width,
  alt = "iaeste lc lleida",
  className,
  style,
  priority,
  sizes,
}: LogoProps) {
  const spec = VARIANTS[variant];
  const w = width ?? spec.defaultWidth;

  return (
    <Image
      src={spec[color]}
      alt={alt}
      width={w}
      height={Math.round(w * spec.ratio)}
      priority={priority}
      sizes={sizes}
      style={style}
      className={cn("h-auto", className)}
    />
  );
}

export default Logo;
