import "@repo/ui/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@repo/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-primary/10">
        <TRPCReactProvider>
          <div className="w-full h-screen flex justify-center">
            <div className="px-4 w-full md:w-[600px] mx-auto">{children}</div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
