export const DEGREE_OPTIONS = [
  "Doble Grau en Organització Industrial i ADE",
  "Doble Grau en Informàtica i ADE",
  "Doble Grau en Mecànica i Energia",
  "Grau en Arquitectura Tècnica",
  "Grau en Disseny Digital",
  "Grau en Enginyeria de l'Energia",
  "Grau en Eng. Electrònica Industrial",
  "Grau en Organització Industrial",
  "Grau en Informàtica (Igualada)",
  "Grau en Informàtica (Lleida)",
  "Grau en Enginyeria Mecànica",
  "Grau en Enginyeria Química",
  "Grau en Tècniques d'Interacció Digital",
  "Altre",
] as const;
