/* tslint:disable */
/* eslint-disable */
/**
 * PLACEHOLDER — this file is normally generated by
 * `npm run --workspace cms generate:types` and must not be hand-edited.
 *
 * It is committed as a hand-written stub only until the Payload packages are
 * installed in CI/dev and the real generator can run against the schema. The
 * shapes below are a faithful subset of what Payload will emit for the four
 * project collections, enough for the public DTO and API routes to typecheck.
 * Regenerate and replace this file wholesale before shipping.
 */

export type PostStatus = "draft" | "published";
export type ContentLocale = "ca" | "es" | "en";

export interface Config {
  locale: ContentLocale;
  collections: {
    users: User;
    posts: Post;
    tags: Tag;
    media: Media;
  };
  db: { defaultIDType: string };
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: "administrator" | "editor";
  disabled?: boolean | null;
  createdAt: string;
  updatedAt: string;
}

export interface MediaSize {
  url?: string | null;
  width?: number | null;
  height?: number | null;
  mimeType?: string | null;
  filesize?: number | null;
  filename?: string | null;
}

export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  sourceNote?: string | null;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  sizes?: {
    card?: MediaSize | null;
    hero?: MediaSize | null;
  } | null;
  createdAt: string;
  updatedAt: string;
}

export interface Tag {
  id: string;
  key: string;
  label?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface Post {
  id: string;
  title?: string | null;
  slug?: string | null;
  excerpt?: string | null;
  body?: SerializedEditorState | null;
  coverImage?: (string | null) | Media;
  tags?: (string | Tag)[] | null;
  author: string;
  publishDate?: string | null;
  legacyTranslationKey?: string | null;
  _status?: PostStatus | null;
  createdAt: string;
  updatedAt: string;
}

/** Payload re-exports this from `@payloadcms/richtext-lexical`. */
export interface SerializedEditorState {
  root: {
    type: string;
    children: unknown[];
    direction: ("ltr" | "rtl") | null;
    format: "" | "left" | "start" | "center" | "right" | "end" | "justify";
    indent: number;
    version: number;
  };
  [k: string]: unknown;
}
